[dev]
  command = "cameronjs dev"
  publish = "publish"
  port = 8080

[build]
  command = "yarn build"
  publish = "publish"
  functions = "functions"

# For more settings see https://www.netlify.com/docs/netlify-toml-reference/#post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# See https://www.netlify.com/docs/netlify-toml-reference/#redirects
[[redirects]]
  from = "/welcome"
  to = "/getting-started/welcome.html"
[[redirects]]
  from = "/layouts"
  to = "/core-concepts/html.html#layouts"
[[redirects]]
  from = "/partials"
  to = "/core-concepts/html.html#partials"
[[redirects]]
  from = "/js"
  to = "/core-concepts/javascript.html"
[[redirects]]
  from = "/stimulus"
  to = "/core-concepts/javascript.html#stimulusjs"
[[redirects]]
  from = "/css"
  to = "/core-concepts/css.html"
[[redirects]]
  from = "/tailwind"
  to = "/core-concepts/css.html#tailwindcss"
[[redirects]]
  from = "/first-app"
  to = "/first-app/intro.html"

# See https://www.netlify.com/docs/netlify-toml-reference/#headers
[[headers]]
